### ISSUE TITLE
Osan 2.1 Tehtävässä "Kertaus" asiavirhe

### ISSUE THREAD

**Issue by lajp** [rage/ohjelmointi-23#3]
Monivalintatehtävässä kysymyksenä on: "Valitse seuraavista vaihtoehdoista ne, jotka ovat Pythonin syntaksin mukaisia."
Yhtenä vaihtoehdoista on `if luku == false:`, joka on merkitty vääräksi vastaukseksi.

Vastaus on kuiteni oikein, sillä käyttäjä voi esimerkiksi määritellä `false`-nimisen muuttujan ja täten verrata muuttujien `luku` ja `false` arvoja.

**Comment by karoliinaheikkinen** [comment]
if luku == false ei ole syntaksin mukainen koska lauseen lopusta puuttuu : (kaksoispiste)

if luku == false : 
vrt. if luku == false

**Comment by lajp** [comment]
Ok, kiitos selvennyksestä
